### ISSUE TITLE
executor: support`BIGINT` datatype

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#477]
Currently, we do not have a i64 expression (except for the RowHandler array). We should support `i64` across our binder, expression and storage layers.

- [ ] Support `BIGINT` in binder
- [ ] Support `BIGINT` expressions
- [ ] Support `BIGINT` in storage layer
- [ ] ~~chore(storage): `RowHandler` should be part of the `I64ColumnIterator`~~

**Comment by Fedomn** [comment]
I'd like to try this

**Comment by skyzh** [comment]
Thanks! You may refer to https://github.com/risinglightdb/risinglight/pull/236 https://github.com/risinglightdb/risinglight/pull/242 and https://github.com/risinglightdb/risinglight/pull/257 for how in the past we add new data types.

**Comment by Fedomn** [comment]
> chore(storage): RowHandler should be part of the I64ColumnIterator

I'm a little confused about the above part, because `I64ColumnIterator` is a subtype of `ConcreteColumnIterator`, however `RowHandlerColumnIterator` is different from `ConcreteColumnIterator`, such as it doesn't have the corresponding `block`.

So maybe we could still keep `RowHandlerColumnIterator`?

**Comment by skyzh** [comment]
You're right. Let's keep the RowHandlerIterator. It's easier to implement when we separate these two iterators.
