### ISSUE TITLE
planner: support group by expression

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#526]
```
select v2 + 1, sum(v1) from t1 group by v2 + 1;
```

... which currently yields:

```
thread 'tokio-runtime-worker' panicked at 'Plus(Column #ColumnRefId { database_id: 0, schema_id: 0, table_id: 8, column_id: 1 }, Int32(1) (const)) cannot be a group key', src/optimizer/logical_plan_rewriter/input_ref_resolver.rs:111:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'failed to join query thread: JoinError::Panic(...)', src/main.rs:106:23
```

**Comment by Fedomn** [comment]
I'd like to try this

**Comment by skyzh** [comment]
This would be hard... I haven't thought of how to achieve this. I think the first problem you will meet is in `InputRefResolver`.

```
select v2 + 1, sum(v1) from t1 group by v2 + 1;
```

In `InputRefResolver`, we will need to bind a `InputRef` for HashAgg. However, in the case of this query, the binding logic should be non-trivial.

I think supporting group-by expression might need a refactor across the binder, planner and optimizer. If you have any idea, I'd suggest first posting it in Slack group / Discussion or this issue.

Thanks @Fedomn !

**Comment by jiangzhe** [comment]
IMO, it's a little tricky to achieve correct name resolution of `GROUP BY` clause(as well as `HAVING`, not mentioned here).
Basically, the resolution logic could follow `WHERE` or `SELECT` clause, which use table list specified in `FROM`.
Then there are two ways to implement the specific logic of `GROUP BY`.
1. Try match entire expression with `SELECT`ed expression list, prior to normal resolution.
2. Instead of changing resolution logic, add post-validation checking whether the non-aggregate expression is in `SELECT`ed list.
One more thing to note: the actual implementations of different databases diverge on how to resolve group items, especially when groups and aggregate functions are mixed in the same expression.
Take MySQL and Oracle as examples.

```sql
CREATE TABLE t1 (c0 int, c1 int);
SELECT c0, c0 + count(*) FROM t1 GROUP BY c0; -- succeeds in both
SELECT c0, c0+1 +count(*) from t1 GROUP BY c0; -- succeeds in both
SELECT c0+1, c0+1 + count(*) FROM t1 GROUP BY c0+1; -- fails in MySQL but succeeds in Oracle
SELECT c0+1, count(*)+c0+1 FROM t1 GROUP BY c0+1; -- fails in both
SELECT c0+1, c0+1+1+count(*) FROM t1 GROUP BY c0+1; -- fails in MySQL but suceeds in Oracle
SELECT c0+1, c0+2+count(*) FROM t1 GROUP BY c0+1; -- fails in both
```
All above cases make sense from human perspective but some cases make the resolution much harder.
MySQL only allow non-aggr part to be composite of columns and constants, if columns belong to groups.
Oracle tries to find non-aggr in already defined groups using exact match.

**Comment by skyzh** [comment]
This is really helpful! Thanks a lot.

**Comment by Fedomn** [comment]
Thanks for all feedback! Through recent investigation, I'd try to summarize my proposal:

1. we follow PostgreSQL `GROUP BY` strict validation, which means: `select_exprs` must appear in the GROUP BY clause or be used in an aggregate function. therefore, we should add validation when building `LogicalAggregate` 
2. to support group by expression, we use `InputRef` to replace original `select_item` in `stmt.select_list` when build `plan_select`. so the SQL `select v2 + 1, sum(v1) from t group by v2 + 1` logical plan will be:
```
PhysicalProjection:
    InputRef #0
    InputRef #1
  PhysicalHashAgg:
      (InputRef #0 + 1)
      sum(InputRef #1) -> INT (null)
    PhysicalTableScan:
        table #8,
        columns [1, 0],
        with_row_handler: false,
        is_sorted: false,
        expr: None
```
3. meanwhile, to resolve higher-level logical plan InputRefesolver, such as `select v2, v2 + 1, sum(v1) from t group by v2 + 1, v2 order by v2`
we change `InputRefResolver.bindings` from `Vec<Option<ColumnRefId>>` type to `Vec<Option<BoundExpr>>`, and then `rewrite_expr` will filter identical expr in bindings , if not found , it will rewrite recursively. So the above sql logical plan will be:
```
PhysicalOrder:
    [InputRef #0 (asc)]
  PhysicalProjection:
      InputRef #1
      InputRef #0
      InputRef #2
    PhysicalHashAgg:
        (InputRef #0 + 1)
        InputRef #0
        sum(InputRef #1) -> INT (null)
      PhysicalTableScan:
          table #8,
          columns [1, 0],
          with_row_handler: false,
          is_sorted: false,
          expr: None
```

**Comment by skyzh** [comment]
Thanks for this explanation! I will take a look into this soon.
