### ISSUE TITLE
catalog: internal table support

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#99]
It would be very helpful if we could know internal states of our storage engine using SQL queries. e.g.

```
SELECT rowset_id, size FROM internal.storage.rowsets WHERE table_id = 1;
```

**Comment by skyzh** [comment]
... maybe our first internal table could be `contributor list`?

**Comment by xxchan** [comment]
I'm wondering how to maintain internal tables.. 

I'm considering a `TableType` for internal tables. For example, `contributor list` can be generated in scripts and passed by `env!`, so it is more like a memory table (or just use `InMemoryTable` directly). But the problem is that each storage engine is bound to its `TableType`, so I cannot use an `InMemoryTable` inside `secondary` engine. If we instead implement internal tables differently for each engine, it is not elegant and maybe is inproper (e.g., `contributor list` doesn't need to be stored on disk).

Another idea is to create a separate engine for internal tables, but it seems that we can only use one engine currently?

**Comment by skyzh** [comment]
Internal tables should be a separate engine. e.g., `InternalTableExecutor`, with different endpoints of our system (e.g., compactor, query engine, etc.) providing `get_statistics(&self) -> DataChunk` API to fetch the content of tables.
